/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Swagger PetStore Clone
 * Reference [OpenAPI example](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml)
 * OpenAPI spec version: 1.0.0
 */

export interface Pet {
  id: number;
  name: string;
  tag?: string;
}
