/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Swagger PetStore Clone
 * Reference [OpenAPI example](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml)
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, delay, http } from "msw";

export const getListPetsMock = () => [
  { id: 0, name: "dog", tag: "tag1" },
  { id: 1, name: "cat", tag: "tag2" },
];

export const getShowPetByIdMock = () => ({ id: 0, name: "dog", tag: "tag1" });

export const getPetsMSW = () => [
  http.get("http://localhost:8080/pets", async () => {
    await delay(10);
    return new HttpResponse(JSON.stringify(getListPetsMock()), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }),
  http.post("http://localhost:8080/pets", async () => {
    await delay(10);
    return new HttpResponse(null, {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }),
  http.get("http://localhost:8080/pets/:petId", async () => {
    await delay(10);
    return new HttpResponse(JSON.stringify(getShowPetByIdMock()), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
    });
  }),
];
